Repository grainymac/whatsCookin, pull requests merged in 2022-11, with the labels that each got.

#48 Add prettier rc file
  .prettierrc
Labels: enhancement

#51 Feature/pantry UI.th
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: ui update

#56 Staging/iteration4
  src/classes/User.js
  src/data/recipeSampleData.js
  src/scripts.js
  test/User-test.js
Labels: enhancement

#58 Bug fix/update user pantry.th
  src/classes/Ingredient.js
  src/classes/User.js
  src/data/ingredientSampleData.js
  src/scripts.js
  test/User-test.js
Labels: refactor

#62 Feature/post add ingredients.th
  src/apiCalls.js
  src/classes/Ingredient.js
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/postRequests.js
  src/scripts.js
Labels: enhancement

#63 Refactor add all ingredients post request
  src/postRequests.js
  src/scripts.js
Labels: refactor

#66 Fix my local code editor merge changes
  src/scripts.js
Labels: fix

#69 Feature/button funcitonality cleanup
  src/apiCalls.js
  src/classes/RecipeRepository.js
  src/classes/User.js
  src/scripts.js
Labels: bug

#72 Bug fix/handle 0 amounts
  src/classes/Ingredient.js
  src/scripts.js
  test/Ingredient-test.js
Labels: fix

#74 Feature/show missing ingredients.th
  dist/index.html
  src/classes/User.js
  src/scripts.js
  src/styles.css
Labels: enhancement

#77 Refactor/remove cook modal.th
  dist/cooking.mp4
  dist/cooking.svg
  dist/grocery-bag.png
  dist/index.html
  src/scripts.js
  src/styles.css
Labels: enhancement, refactor
